// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCykygGfuqoW2XeLzE2fUPOncmNB2zo8r4',
    appId: '1:934681634940:web:007628bc2ca9b3e0c3c1f9',
    messagingSenderId: '934681634940',
    projectId: 'movie-app-ceec7',
    authDomain: 'movie-app-ceec7.firebaseapp.com',
    storageBucket: 'movie-app-ceec7.firebasestorage.app',
    measurementId: 'G-78118JDBGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGd6g15M5IkLBno7pKdAKeBlHQ-a4yXAs',
    appId: '1:934681634940:android:b5e8b5f70f757008c3c1f9',
    messagingSenderId: '934681634940',
    projectId: 'movie-app-ceec7',
    storageBucket: 'movie-app-ceec7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkFvgWuXZj-DMzkVLnHe0yojgcB1UNQf0',
    appId: '1:934681634940:ios:fd5f1dd35f886f5ac3c1f9',
    messagingSenderId: '934681634940',
    projectId: 'movie-app-ceec7',
    storageBucket: 'movie-app-ceec7.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkFvgWuXZj-DMzkVLnHe0yojgcB1UNQf0',
    appId: '1:934681634940:ios:fd5f1dd35f886f5ac3c1f9',
    messagingSenderId: '934681634940',
    projectId: 'movie-app-ceec7',
    storageBucket: 'movie-app-ceec7.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCykygGfuqoW2XeLzE2fUPOncmNB2zo8r4',
    appId: '1:934681634940:web:f5ae522daf029527c3c1f9',
    messagingSenderId: '934681634940',
    projectId: 'movie-app-ceec7',
    authDomain: 'movie-app-ceec7.firebaseapp.com',
    storageBucket: 'movie-app-ceec7.firebasestorage.app',
    measurementId: 'G-RDRGFW3RMS',
  );
}
